---
# See https://github.com/jvautier/project-cli
fullname: jvautier/ansible-role-wireguard
description: Install wireguard through ansible
tags:
  - ansible
  - ansible-role
  - wireguard
github:
  has_issues: true
  has_projects: false
  has_wiki: false
